name: tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  tests:
    name: Java ${{ matrix.java-version }} ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        java-distribution: [adopt]
        java-version: [8, 11, 15]

    steps:
      - uses: actions/checkout@v2.1.1
        with:
          submodules: recursive

      - uses: actions/setup-java@v2
        with:
          distribution: "${{ matrix.java-distribution }}"
          java-version: "${{ matrix.java-version }}"

      - uses: actions/cache@v2
        id: maven-cache
        with:
          path: ~/.m2/
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Format check
        if: ${{ matrix.java-version != 8 }}
        run: mvn com.spotify.fmt:fmt-maven-plugin:check

      - name: Tests
        run: mvn -B -V clean test site

      - name: Check for uncommitted changes
        run: git diff --exit-code

  tests-coverage:
    name: Java (Coverage) ${{ matrix.java-version }} ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        java-distribution: [adopt]
        java-version: [11]

    steps:
      - uses: actions/checkout@v2.1.1
        with:
          submodules: recursive

      - uses: actions/setup-java@v2
        with:
          distribution: "${{ matrix.java-distribution }}"
          java-version: "${{ matrix.java-version }}"

      - uses: actions/cache@v2
        id: maven-cache
        with:
          path: ~/.m2/
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Coverage report
        env:
          CI_NAME: github
          COVERALLS_SECRET: ${{ secrets.GITHUB_TOKEN }}
        run: |
          mvn clean test jacoco:report coveralls:report --no-transfer-progress -DrepoToken=$COVERALLS_SECRET -DpullRequest=${{ github.event.number }}
